spring:
  datasource:
    url: jdbc:mysql://43.200.85.14:3306/blood_donation
    username: user
    password: shyu0220
  mvc:
    hidden-method:
      filter:
        enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    cache: true
    prefix: classpath:/templates/



