spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blood_donation
    username: root
    password: shyu0220
  mvc:
    hidden-method:
      filter:
        enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    cache: true
    prefix: classpath:/templates/

server:
  port: 8086

