spring:
  datasource:
    Driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blood-donation.c9zurdezvbur.ap-northeast-1.rds.amazonaws.com:3306/blood_donation?characterEncoding=UTF-8&serverTimezone=UTC&
    username: root
    password: shyu0220

  mvc:
    hidden-method:
      filter:
        enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    cache: true
    prefix: classpath:/templates/

server:
  port: 8086

